chat/urls.py
from django.urls import  path
from . import  views
app_name = "chats"
urlpatterns = [
    path('',views.inbox, name="chat"),
    path('<int:user_id>',views.inbox_message, name="chat"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_view, name="home_page"),
    path('profile/<slug:slug>/', views.profile_detail_view, name="profile_page"),
    path('notifications/', views.notifications_view, name="notifications"),
    path('interested/<slug:slug>/', views.interested_action, name="interested"),
    path('theme_swap/', views.theme_swap_action, name="theme-swap"),
]

hooke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('home.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Interests(models.Model):
    """
    ### Keeps a table of those people who are clickin the interested button
    """
    seeker = models.ForeignKey(User, default=None, on_delete=models.CASCADE, related_name='intereted')
    seeked = models.ForeignKey(User, default=None, on_delete=models.CASCADE, related_name='seeked')
     
    def __str__(self):
        return self.seeker.username
    
class Notifications(models.Model):
    """
    ### Keeps a log of notifications
    """
    from_user = models.ForeignKey(User, default=None, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(User, default=None, on_delete=models.CASCADE, related_name='to_user')
    type = models.CharField(max_length=10) # like or like-back
    status = models.CharField(max_length=10, default="unread") # read / unread
    date = models.DateTimeField(auto_now_add=True, null=True)
     
    
        

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from accounts.models import Profile
from chat.models import Inbox
from .models import Interests, Notifications
from django.contrib.auth import get_user_model

# Create your views here.

@login_required(login_url='/accounts/login/')
def home_view(requests):
    hookies = Profile.objects.exclude(owner=requests.user)
    interests = Interests.objects.filter(seeker=requests.user)
    # if interests.count() == 0:
    #     to_omit = []
    # else:
    #     to_omit = interests

    
    return render(requests, 'home/home.html', {'hookies':hookies, 'to_omit': interests})

def notifications_view(requests):
    notifcations = Notifications.objects.filter(to_user=requests.user)
    return render(requests, 'home/notifications.html', {'notifications': notifcations})

@login_required(login_url='/accounts/login/')
def profile_detail_view(requests, slug):
    profile = Profile.objects.get(owner=slug)
    hostels = Profile.hostels
    schools = Profile.schools
    return render(requests, 'home/profile.html', {'hookie':profile, 'hostels': hostels, 'schools': schools})


@login_required(login_url='/accounts/login/')
def interested_action(requests, slug):
    User = get_user_model()
    seeked_id = User.objects.get(id=slug)

    notification_entry = Notifications()
    notification_entry.from_user = requests.user
    notification_entry.to_user = seeked_id

    # for the type we need to check wheter its a like or a like back
    interests =  Interests.objects.filter(seeked_id=requests.user, seeker=seeked_id)
    if interests.count() != 0:
        # it should be a like back
         notification_entry.type = "like-back"
        # these two can now chat
         inbox = Inbox(user1 = requests.user, user2 = seeked_id)
         inbox.save()
    else:
        # its a like
        notification_entry.type = "like"
    notification_entry.save()

    entry = Interests()
    entry.seeker = requests.user
    entry.seeked = seeked_id
    
    
    entry.save()
    return redirect('home:home_page')

@login_required(login_url='/accounts/login/')
def theme_swap_action(requests):
    try:
        if requests.session['theme'] =="dark":
            requests.session['theme'] = "light"
        else:
            requests.session['theme'] = "dark"
    except:
        requests.session['theme'] = "dark"
    # if 'theme' in requests.session:
    #     if requests.session['theme'] == "dark":
            
    #     else:
    #         requests.session['theme'] = "dark"
    return redirect(requests.META.get('HTTP_REFERER'))

home/templates/home/home.html
{% extends 'home_base_layout.html' %}

{% block content %}
  <nav>
    <div class="px-2 py-2 primary-bg fixed-top" id="header">
      <button class="btn on-surface-text"><i class="fa-solid fa-circle-user fa-lg"></i> Me</b>
      <button class="btn on-surface-text"  style="float: right;"><a class="unstyled" href="{% url 'home:theme-swap' %}"><i class="fa-solid fa-moon fa-lg"></i> Toggle theme</a></button>
    </div>
  </nav>

    <main>
      <br>
        <!-- <section> -->
          <!-- <ul class="list instructions">
            <li class="list-item">
              <i class="fa-solid fa-up-long" style="margin-right: 1.2rem;"></i>Swipe up to see next hookie
              </li>
            <li class="list-item">
              <i class="fa-solid fa-left-long"></i>
              Swipe left to message hookie
            </li>
            <li class="list-item">
              <i class="fa-solid fa-right-long"></i>
              Swipe swipe right to see profile
            </li>
          </ul> -->
        <!-- </section> -->
        
        <section class="main-section container">
          {% for hookie in hookies %}
          
         
            <div class="card card-1 surface surface-border">
              <div class="card-body">
                <div class="image" style="background-image: url('{{ hookie.profile_photo.url }}');"></div>
                <h5 class="on-surface-heading">{{ hookie.first_name }} {{ hookie.last_name }}</h5>
                <p class="on-surface-text">{{ hookie.bio }}</p>
                <p style="text-align:center">
                  <a href="{% url 'home:interested' slug=hookie.owner.id %}" class="btn secondary-color"><i class="fa-regular fa-heart"></i> Interested</a>
                  <a href="{% url 'home:profile_page' slug=hookie.owner.id %}" class="btn on-surface-text"><i class="fa-solid fa-circle-info"></i> View profile</a>

                </p>
                
              </div>
            </div>
          {% endfor %}
            
        </section>
        <br>
        <br>
        <br>
        <br>
    </main>

{% endblock  %}

home/templates/home/notifications.html
{% extends 'home_base_layout.html' %}

{% block content %}
  <nav>
    <div class="px-2 py-2 primary-bg fixed-top" id="header">
      <a href="javascript:history.go(-1)" class="btn on-surface-text"><i class="fa-solid fa-arrow-left fa-lg"></i> Notifications</a>
      <button class="btn on-surface-text"  style="float: right;"><a class="unstyled" href="{% url 'home:theme-swap' %}"><i class="fa-solid fa-moon fa-lg"></i> Toggle theme</a></button>
    </div>
  </nav>

    <main>
        <!-- <section> -->
          <!-- <ul class="list instructions">
            <li class="list-item">
              <i class="fa-solid fa-up-long" style="margin-right: 1.2rem;"></i>Swipe up to see next hookie
              </li>
            <li class="list-item">
              <i class="fa-solid fa-left-long"></i>
              Swipe left to message hookie
            </li>
            <li class="list-item">
              <i class="fa-solid fa-right-long"></i>
              Swipe swipe right to see profile
            </li>
          </ul> -->
        <!-- </section> -->
        
        <section class="main-section container mt-5 pt-3">
         
          <div class="card-1 surface" style="text-align:left;margin:0 auto;width:100%">
            <div class="card-body p-5">
              <h3 class="on-surface-heading">Notifications</h3>
              <ul class="list-group surface list-group-flush">
                {% for alert in notifications %}
                <a href="{% url 'home:profile_page' slug=alert.from_user.id %}" class="list-group-item surface on-surface-heading">
      
                  <i class="fa-regular fa-heart"></i> 
                      <span class="secondary-color" style="font-weight: 600;">{{ alert.from_user.username }}</span>
                        {% if alert.type == "like" %}
                          is interested in you
                        {% else %}
                          who you are interested in liked you back, you can now chat in messages
                        {% endif %}
                      </a>  
                {% endfor %}
              </ul>
            </div>
            
          </div>
         

            
        </section>
        <br>
        <br>
        <br>
        <br>
    </main>


{% endblock  %}

home/templates/home/profile.html
{% extends 'home_base_layout.html' %}

{% block content %}
  <nav>
    <div class="px-2 py-2 primary-bg fixed-top" id="header">
      <a href="javascript:history.go(-1)" class="btn on-surface-text"><i class="fa-solid fa-arrow-left fa-lg"></i> Profile</a>
      <button class="btn on-surface-text"  style="float: right;"><a class="unstyled" href="{% url 'home:theme-swap' %}"><i class="fa-solid fa-moon fa-lg"></i> Toggle theme</a></button>
    </div>
  </nav>

    <main>
      <br>
        
        <section class="main-section container-profile surface surface-border on-surface-heading">
            <div class="image profile-picture" style="background-image: url('{{ hookie.profile_photo.url }}');"></div>
              <h5 class="on-surface-heading">{{ hookie.first_name }} {{ hookie.last_name }}</h5>
              <p class="on-surface-text px-3" style="text-align:center">{{ hookie.bio }}</p>
              <p style="text-align:center">
                <a href="{% url 'home:interested' slug=hookie.owner.id %}" class="btn secondary-color"><i class="fa-regular fa-heart"></i> Interested</a>
              </p>
       
        <div class="field-container " >
            <label class="form-label " for="Number">
                &#x1F4DE Phone Number:</label>
                <input type="tel" class="user-input on-surface-heading" readonly="" value="{{ hookie.phone_number }}"  placeholder="Contact">
                <i  id="edit-icon3" class="fas fa-pencil-alt edit-icons" style="display: none;"></i>
        </div>
        <div class="field-container">
            <label class="form-label" for="age">
                &#x1F5D3 Date of birth: </label>
                <input class="user-input on-surface-heading" type="text" value="{{ hookie.date_of_birth }}" readonly="">
            </div>
        <div class="field-container">
            <label class="form-label" for="Bio">
                 &#x1F4DD Nationality: </label>
                <input type="text" class="user-input on-surface-heading" readonly="" value="{{ hookie.nationality }}" placeholder="About me">
                <i id="edit-icon4" class="fas fa-pencil-alt edit-icons" style="display: none;"></i>
        </div>
        <div class="field-container">
            <label class="form-label" for="Bio">
                 &#x1F4DD Hostel: </label>
                <input type="text" class="user-input on-surface-heading" readonly="" value="{{ hookie.hostel }}" placeholder="About me">
                <i id="edit-icon4" class="fas fa-pencil-alt edit-icons" style="display: none;"></i>
        </div>
        <div class="field-container">
            <label class="form-label" for="Bio">
                 &#x1F4DD School: </label>
                <input type="text" class="user-input on-surface-heading" readonly="" value="{{ hookie.school }}" placeholder="About me">
                <i id="edit-icon4" class="fas fa-pencil-alt edit-icons" style="display: none;"></i>
        </div>
        <div class="field-container">
            <label class="form-label" for="Bio">
                 &#x1F4DD Program of study: </label>
                <input type="text" class="user-input on-surface-heading" readonly="" value="{{ hookie.program }}" placeholder="About me">
                <i id="edit-icon4" class="fas fa-pencil-alt edit-icons" style="display: none;"></i>
        </div>
        {% comment %} <div style="margin-left:auto;">
            <button class="btn btn-primary edit-button" type="button" 
                style="padding: 5px 10px;background-color: transparent;border:1px solid #ffd3a5;color: initial;">
                Edit Profile &#x270F
            </button>
            <button class="btn btn-primary save-button" type="button"
                style="padding: 5px 10px;background-color: transparent;border: 1px solid #ffd3a5;color: initial;display:none;">
                Save &#x2713
            </button>
        </div> {% endcomment %}
      
            
        </section>
        <br>
        <br>
        <br>
        <br>
    </main>

  
{% endblock  %}