accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('create-profile/', views.create_profile_view, name="create-profile"),
]

chat/urls.py
from django.urls import  path
from . import  views
app_name = "chats"
urlpatterns = [
    path('',views.inbox, name="chat"),
    path('<int:user_id>',views.inbox_message, name="chat"),
]

hooke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('home.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
  nationalities = [
    ('Zambian', 'Zambian'),
    ('Malawian', 'Malawian'),
    ('South African', 'South African'),
    ('Zimbabwean', 'Zimbabwean'),
    ('Congolis', 'Congolis'),
    ('Indian', 'Indian'),
    ('Chinese', 'Chinese'),
    ('Moroccan', 'Moroccan'),
    ('Botswanan', 'Botswanan'),
    ('Nigerian', 'Nigerian'),
  ]
  hostels = [
    ('Kalingalinga', 'Kalingalinga'),
    ('Tiyende Pamodzi', 'Tiyende Pamodzi'),
    ('Soweto', 'Soweto'),
    ('Kafue', 'Kafue'),
    ('October', 'October'),
    ('Zambezi', 'Zambezi'),
    ('International', 'International'),
    ('President', 'President'),
    ('Kwacha', 'Kwacha'),
    ('Africa', 'Africa'),
    ('VET', 'VET'),
    ('Levy Mwanawas', 'Levy Mwanawasa'),
  ]
  schools = [
    ('Natural Sciences', 'Natural Sciences'),
    ('Agricultural Sciences', 'Agricultural Sciences'),
    ('Mines', 'Mines'),
    ('Education', 'Education'),
    ('Humaninities and Social Sciences', 'Humaninities and Social Sciences'),
    ('Engineering', 'Engineering'),
    ('Vetnery Medicine', 'Vetnery Medicine'),
    ('Confucius Studies', 'Confucius Studies'),
    ('Law', 'Law'),
  ]
  first_name = models.CharField(max_length=50)
  last_name = models.CharField(max_length=50)
  phone_number = models.CharField(max_length=12)
  bio = models.CharField(max_length=150, help_text="Enter a brief description of yourself", null=True)
  # gender
  date_of_birth = models.DateField()
  nationality = models.CharField(max_length=50, choices=nationalities, default="Za")
  hostel = models.CharField(max_length=50, choices=hostels, default="Ka")
  school = models.CharField(max_length=50, choices=schools, default="Na")
  program = models.CharField(max_length=100)
  year = models.CharField(max_length=5)
  owner = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
  profile_photo = models.ImageField(default='default.jpg', blank=True, null=True, upload_to="profile_pictures/")
  # add in thumbnail later
  # add in author later

  def __str__(self):
        return self.first_name + " " + self.last_name
  

accounts/forms.py
from django import forms
from . import models

class Profile_form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['date_of_birth'].widget.attrs['id'] = 'date'
        self.fields['date_of_birth'].widget = forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)'
                }
            )

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            # visible.field.widget.attrs['placeholder'] = visible.field.label
    class Meta:
        model = models.Profile
        fields = ['first_name', 'last_name', 'phone_number', 'bio', 'date_of_birth', 'nationality', 
                  'hostel', 'school', 'program', 'year', 'profile_photo']
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
from .models import Profile
from . import forms
from django.contrib.auth.decorators import login_required
# Create your views here.
def signup_view(requests):
  if requests.method == 'POST':
    form = UserCreationForm(requests.POST)
    if form.is_valid():
      user = form.save()
      login(requests, user)
      return redirect('accounts:create-profile')

  else:
    form = UserCreationForm()  
  return render(requests, 'accounts/signup.html', { 'form': form })

def login_view(requests):
  if requests.method == 'POST':
    form = AuthenticationForm(data=requests.POST)
    if form.is_valid():
      user = form.get_user()
      login(requests, user)
      return redirect('home:home_page')
  else:
    form = AuthenticationForm()  
  return render(requests, 'accounts/login.html', { 'form': form })

@login_required(login_url='/accounts/login/')
def create_profile_view(requests):
  if requests.method == "POST":
    profile_form = forms.Profile_form(requests.POST, requests.FILES)
    if profile_form.is_valid():
      # save to db
      instance = profile_form.save(commit=False)
      instance.owner = requests.user
      instance.save()
      return redirect('home:home_page')
  else:
    profile_form = forms.Profile_form()
  return render(requests, 'accounts/create_profile.html', {'form': profile_form})

accounts/templates/accounts/create_profile.html
{% extends 'base_accounts_layout.html' %}

{% block content %}
<h1>Hooke</h1>
  <h3 class="card-title">Complete Profile</h3>
    <form class="site-form" method="post" action="{% url 'accounts:create-profile' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      
      <p class="p-button mt-2">
        <button class="btn" type="submit" value="Signup" style="--bs-primary: #772244;--bs-primary-rgb: 119,34,68;--bs-body-bg: #3c1d08;--bs-secondary: rgb(250,223,154);--bs-secondary-rgb: 250,223,154;background: #772244;">Signup</button>
      </p>
    </form>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base_accounts_layout.html' %}

{% block content %}
<h1>Hooke</h1>
  <h3 class="card-title">Log in</h3>
    <form class="site-form" method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}
      {{ form }}
      
      <p class="p-button mt-2">
        <button class="btn" type="submit" value="Signup" style="--bs-primary: #772244;--bs-primary-rgb: 119,34,68;--bs-body-bg: #3c1d08;--bs-secondary: rgb(250,223,154);--bs-secondary-rgb: 250,223,154;background: #772244;">Log in</button>
      </p>
    </form>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base_accounts_layout.html' %}

{% block content %}
<h1>Hooke</h1>
  <h3 class="card-title">Signup</h3>
    <form class="site-form" method="post" action="{% url 'accounts:signup' %}">
      {% csrf_token %}
      {{ form }}
      
      <p class="p-button mt-2">
        <button class="btn" type="submit" value="Signup" style="--bs-primary: #772244;--bs-primary-rgb: 119,34,68;--bs-body-bg: #3c1d08;--bs-secondary: rgb(250,223,154);--bs-secondary-rgb: 250,223,154;background: #772244;">Signup</button>
      </p>
    </form>
{% endblock  %}