chat/urls.py
from django.urls import  path
from . import  views
app_name = "chats"
urlpatterns = [
    path('',views.inbox, name="chat"),
    path('<int:user_id>',views.inbox_message, name="chat"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_view, name="home_page"),
    path('profile/<slug:slug>/', views.profile_detail_view, name="profile_page"),
    path('notifications/', views.notifications_view, name="notifications"),
    path('interested/<slug:slug>/', views.interested_action, name="interested"),
    path('theme_swap/', views.theme_swap_action, name="theme-swap"),
]

hooke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('home.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_accounts_layout.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hooke - Auth</title>
    <link rel="stylesheet" href="{% static 'accounts/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/styles.css' %}">

   
  </head>
  <body>
    <main>
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
              {% block content %}

              {% endblock %}
                
            </div>
        </div>
    </div>
</main>
  


  
  </body>
</html>

templates/home_base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>home</title>
    <link rel="stylesheet" href="{% static 'home/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/theme.css' %}">
    <link rel="stylesheet" href="{% static 'home/dashboard.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css">
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" /> {% endcomment %}
    <script src="{% static 'home/jquery-3.6.4.js' %}"></script>
    <script src="{% static 'home/dashboard.js' %}"></script>
   
</head>
{% if request.session.theme == "dark" %}
<body class="dark-theme" id="page">
{% else %}
<body class="light-theme" id="page">
{% endif %}

  <div id="screen">
    <section id="side-menu" class="pt-5">
      <div class="card surface surface-border mt-3">
        <nav class="nav flex-column">
          <a class="nav-link active mobile-bottom-nav__item--active" href="{% url 'home:home_page' %}"><i class="fa-solid fa-home"></i> Home</a>
          <a class="nav-link on-surface-text" href="{% url 'chats:chat' %}"><i class="fa-solid fa-message"></i>
            Messages</a>
          <a class="nav-link on-surface-text" href="{% url 'home:notifications' %}"><i class="fa-solid fa-bell"></i>
            Notifications</a>
        </nav>
      </div>
      
    </section>
    <section id="main-content">
      {% block content %}

      {% endblock %}
    </section>
    <section id="space"></div>
  </div>
 
  
  
  <nav class="mobile-bottom-nav surface">
    
    <div class="mobile-bottom-nav__item mobile-bottom-nav__item--active">
      <a class='unstyled' href="{% url 'home:home_page' %}">
      <div class="mobile-bottom-nav__item-content">
        <i class="fa-solid fa-home"></i>
        home
      </div>	
    </a>	
    </div>
    <div class="mobile-bottom-nav__item">		
      <a class='unstyled' href="{% url 'chats:chat' %}">
      <div class="mobile-bottom-nav__item-content on-surface-text">
        <i class="fa-solid fa-message"></i>
        Messages
      </div>
    </a>
    </div>
    <div class="mobile-bottom-nav__item">
      <a class='unstyled' href="{% url 'home:notifications' %}">
        <div class="mobile-bottom-nav__item-content on-surface-text">
          <i class="fa-solid fa-bell"></i>
          Notifications
        </div>	
      </a>
        
    </div>
    </nav> 
    <script src="{% static 'home/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>